language: generic

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils
  - git submodule update --init

script:
  - make
  - make test
os:
  - linux

git:
  submodules: false #we don't want to clone recursively
